name: Scan

on:
  workflow_dispatch:

permissions: {}

jobs:
  accessibility_scanner:
    name: Accessibility Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        id: generate_cache_key
        shell: bash
        run: |
          CACHE_KEY=$(printf 'cached_results-hi-state-services-%s.json' "${{ github.ref_name }}" | tr -cs 'A-Za-z0-9._-' '_')
          echo "cache_key=$CACHE_KEY" >> $GITHUB_OUTPUT
      - uses: github/accessibility-scanner@v3
        with:
          urls: |
            https://black-mud-081305f0f.7.azurestaticapps.net
            https://black-mud-081305f0f.7.azurestaticapps.net/services/
            https://black-mud-081305f0f.7.azurestaticapps.net/departments/
            https://black-mud-081305f0f.7.azurestaticapps.net/forms/
            https://black-mud-081305f0f.7.azurestaticapps.net/about/
          repository: anabil25/hi-state-services
          cache_key: ${{ steps.generate_cache_key.outputs.cache_key }}
          token: ${{ secrets.GH_TOKEN }}
          include_screenshots: true
          scans: '["axe","reflow-scan"]'
